### ISSUE TITLE
ModuleNotFoundError: No module named 'FDSC'

### ISSUE THREAD

**Issue by hufangjian** [MohamedSebaie/Fight_Detection_From_Surveillance_Cameras-PyTorch_Project#1]
I run 
python -m infer \
--modelPath="./Models/model_16_m3_0.8888.pth" \
--streaming=False \
--inputPath="./dataset/fight/fi148.mp4" \
--outputPath="./outputVideo.mp4" \
--sequenceLength=16 \
--skip=2 \
--showInfo=True

get this error！

**Comment by dongxiaolong** [comment]
you can fix the bug by change  infer.py line 2 to `from FDSC.Fight_utils import loadModel, predict_on_video, start_streaming `  while you should change the dir UtilsFiles to FDSC.

**Comment by LemonCANDY42** [comment]
> you can fix the bug by change infer.py line 2 to `from FDSC.Fight_utils import loadModel, predict_on_video, start_streaming ` while you should change the dir UtilsFiles to FDSC.

Excellent! it's solved my problem.
