### ISSUE TITLE
Problem when Download Finetuned Model Weights

### ISSUE THREAD

**Issue by khiempg** [MohamedSebaie/Fight_Detection_From_Surveillance_Cameras-PyTorch_Project#3]
Hello,
Thank for interesting project.
But I can not download Finetuned Model Weights, can you share it again ?
https://drive.google.com/uc?id=1MWDeLnpEaZDrKK-OjmzvYLxfjwp-GDcp
above link is not available anymore, please check.

Thank you!

**Comment by ghost** [comment]
same here have you got any reply or drive link
